<h1>Фотогалерея</h1>
	<a href="i/1.jpg" rel="prettyPhoto[gallery]"><img src="i/thumbs/1.jpg" alt=""/></a>
	<a href="i/1.jpg" rel="prettyPhoto[gallery]"><img src="i/thumbs/1.jpg" alt=""/></a>
	<a href="i/1.jpg" rel="prettyPhoto[gallery]"><img src="i/thumbs/1.jpg" alt=""/></a>
	<a href="i/1.jpg" rel="prettyPhoto[gallery]"><img src="i/thumbs/1.jpg" alt=""/></a>
	<a href="i/1.jpg" rel="prettyPhoto[gallery]"><img src="i/thumbs/1.jpg" alt=""/></a>
	<a href="i/1.jpg" rel="prettyPhoto[gallery]"><img src="i/thumbs/1.jpg" alt=""/></a>
	<a href="i/1.jpg" rel="prettyPhoto[gallery]"><img src="i/thumbs/1.jpg" alt=""/></a>
	<a href="i/1.jpg" rel="prettyPhoto[gallery]"><img src="i/thumbs/1.jpg" alt=""/></a>
	<a href="i/1.jpg" rel="prettyPhoto[gallery]"><img src="i/thumbs/1.jpg" alt=""/></a>
	<a href="i/1.jpg" rel="prettyPhoto[gallery]"><img src="i/thumbs/1.jpg" alt=""/></a>
	<a href="i/swf.swf?width=400&height=400" rel="prettyPhoto"><img src="i/thumbs/swf.jpg" alt=""/></a>