<form name="addcomment" method="post" action="<?=$site->pageUrl;?>" enctype="multipart/form-data" data-request="ajax" class="form" data-request="ajax">
	<input type="hidden" name="key" value="">

	<label for="text" class="label"><span class="alert">*</span> <?=$form->text->title;?>:</label>
	<textarea id="text" name="text" rows="10" cols="17" required class="textarea"><?=$form->text->getDisplayValue();?></textarea>
	<div class="alert"><?=$form->text->error;?></div>

	<label for="name" class="label"><span class="alert">*</span> <?=$form->name->title;?>:</label>
	<input id="name" name="name" type="text" maxlength="255" value="<?=$form->name->getDisplayValue();?>" required class="input">
	<div class="alert"><?=$form->name->error;?></div>

	<label for="email" class="label"><?=$form->email->title;?>:</label>
	<input id="email" name="email" type="text" maxlength="255" value="<?=$form->email->getDisplayValue();?>" class="input">
	<div class="alert"><?=$form->email->error;?></div>

	<button type="submit" class="submit">Отправить</button>
	<div class="alert"><?=$form->error;?></div>
</form>