<h3><?=$cat['title']?></h3>
<ul class="ns">
	<? if ($items): ?>
		<? foreach ($items as $item_params): ?>
			<li id="item<?=$item_params['id'];?>">
				<? if ($site->getUserAccess() >= $config['access']['edit']): ?>
                    <a href="/<?=$site->module;?>/edit/<?=$item_params['id'];?>" class="comment"><i class="icon-pencil"></i></a>
				<? endif; ?>
				<? if ($site->getUserAccess() >= $config['access']['del']): ?>
					<a href="/<?=$site->module;?>/del/<?=$item_params['id'];?>" class="comment" data-request="ajax" data-confirm="item-del"><i class="icon-trash"></i></a>
				<? endif; ?>
				&nbsp; <a href="/<?=$site->module;?>/item/<?=$item_params['id'];?>"><?=$item_params['title'];?></a>
			</li>
		<? endforeach; ?>
	<? else: ?>
		<li>Данных нет</li>
	<? endif; ?>
</ul>
<?=$pager;?>
<? if ($site->getUserAccess() >= $config['access']['add']): ?>
	<p><a href="/<?=$site->module;?>/add">Добавить</a></p>
<? endif; ?>