<? if ($site->getUserAccess() > 3): ?>
    <script src="/js/jwysiwyg/jquery.wysiwyg.js"></script>
    <script src="/js/jwysiwyg/controls/wysiwyg.image.js"></script>
    <script src="/js/jwysiwyg/controls/wysiwyg.link.js"></script>
    <script src="/js/jwysiwyg/controls/wysiwyg.table.js"></script>
    <script src="/<?=$site->module?>/js/wysiwyg.js?<?=$site->version;?>"></script>
<? endif; ?>
<script src="/<?=$site->module?>/edit/script.js?<?=$site->version;?>"></script>