<h3><?=$form->title->getDisplayValue();?></h3>
<? if (!empty($form->image->value)): ?>
	<a href="/<?=$site->module;?>/data/items/i/<?=$form->image->value;?>" rel="lightbox"><img src="/<?=$site->module;?>/data/items/i/thumbs/<?=$form->image->value;?>" alt="<?=$form->title->getDisplayValue();?>" class="image floatright"></a>
<? endif; ?>
<?
echo isset($config['items'])
	? $form->text->value
	: file_get_contents($site->moduleItemsPath . '/content/' . $id . '.html');
echo '<br>';
if (!empty($form->price->value)) echo $form->price->title . ': ' . $form->price->getDisplayValue() . '<br>';
if (!empty($form->name->value)) echo $form->name->title . ': ' . $form->name->getDisplayValue() . '<br>';
if (!empty($form->phone->value)) echo $form->phone->title . ': ' . $form->phone->getDisplayValue() . '<br>';
if (!empty($form->icq->value)) echo $form->icq->title . ': ' . $form->icq->getDisplayValue() . '<br>';
if (!empty($form->skype->value)) echo $form->skype->title . ': <a href="callto:' . $form->skype->getDisplayValue() . '">' . $form->skype->getDisplayValue() . '</a><br>';
if (!empty($form->url->value)) echo $form->url->title . ': <a href="' . $form->url->getDisplayValue() . '" target="_blank">' . $form->url->getDisplayValue() . '</a><br>';
if (!empty($form->email->value)) echo $form->email->title . ': <a href="mailto:' . $form->email->getDisplayValue() . '">' . $form->email->getDisplayValue() . '</a><br>';
if (!empty($form->city->value)) echo $form->city->title . ': ' . $form->city->getDisplayValue() . '<br>';
if (!empty($form->zip->value)) echo $form->zip->title . ': ' . $form->zip->getDisplayValue() . '<br>';
if (!empty($form->address->value)) echo $form->address->title . ': ' . $form->address->getDisplayValue() . '<br>';
if (!empty($form->company->value)) echo $form->company->title . ': ' . $form->company->getDisplayValue() . '<br>';
if (!empty($form->occupation->value)) echo $form->occupation->title . ': ' . $form->occupation->getDisplayValue() . '<br>';
?>
<? if (!empty($form->file->value)): ?>
	<p><a href="/<?=$site->module;?>/data/items/<?=$form->file->value;?>"><?=$form->file->getDisplayValue();?></a></p>
<? endif; ?>
<? if (!empty($form->date->value)) echo Date::sqlToDate($form->date->value); ?>

<? if (isset($config['comments'])): ?>
<h4>Комментарии</h4>
<p><a href="/<?=$site->module;?>/addcomment/?item=<?=$id;?>">Добавить комментарий</a></p>
<? if ($comments): ?>
	<? foreach ($comments as $comment_params): ?>
		<p id="comment<?=$comment_params['id'];?>">
			<strong>
				<? if (!empty($comment_params['email'])): ?>
					<a href="mailto:<?=$comment_params['email'];?>"><?=$comment_params['name'];?></a>
				<? else: ?>
					<?=$comment_params['name'];?>
				<? endif; ?>
			</strong><br>
			<?=$comment_params['text'];?>
		</p>
	<? endforeach; ?>
<? else: ?>
	<p>Комментариев нет</p>
<? endif; ?>

<? endif; ?>