$(function() {
    $('#text').wysiwyg({
        controls : {
            bold : { visible : true },
            italic : { visible : true },
            strikeThrough : { visible : true },
            underline : { visible : true },
            separator00 : { visible : true },
            justifyLeft : { visible : true },
            justifyCenter : { visible : true },
            justifyRight : { visible : true },
            justifyFull : { visible : true },
            separator01 : { visible : true },
            indent : { visible : true },
            outdent : { visible : true },
            separator02 : { visible : true },
            subscript : { visible : true },
            superscript : { visible : true },
            separator03 : { visible : true },
            undo : { visible : true },
            redo : { visible : true },
            separator04 : { visible : true },
            insertOrderedList : { visible : true },
            insertUnorderedList : { visible : true },
            insertHorizontalRule : { visible : true },
            separator05 : { visible : true },
            createLink : { visible : true },
            insertImage : { visible : true },
            separator06 : { visible : true },
            h1mozilla : { visible : true },
            h2mozilla  : { visible : true },
            h3mozilla  : { visible : true },
            h1 : { visible : true },
            h2 : { visible : true },
            h3: { visible : true },
            separator07 : { visible : true },
            cut : { visible : true },
            copy : { visible : true },
            paste : { visible : true },
            separator08 : { visible : true },
            increaseFontSize : { visible : true },
            decreaseFontSize : { visible : true },
            separator09 : { visible : true },
            html : { visible : true },
            removeFormat : { visible : true }
        }
    });
});