<h1>Обратная связь</h1>
<form name="<?=$site->module;?>" method="post" action="<?=$site->pageUrl;?>" enctype="multipart/form-data" class="form">
	<input type="hidden" name="key" value="">

	<label for="title" class="label"><span class="alert">*</span> <?=$form->title->title;?>:</label>
	<input id="title" name="title" type="text" maxlength="255" value="<?=$form->title->getDisplayValue();?>" required class="input">
	<div class="alert"><?=$form->title->error;?></div>

	<label for="text" class="label"><?=$form->text->title;?>:</label>
	<textarea id="text" name="text" rows="10" cols="17" class="textarea"><?=$form->text->getDisplayValue();?></textarea>
	<div class="alert"><?=$form->text->error;?></div>

	<label for="price" class="label"><?=$form->price->title;?>:</label>
	<input id="price" name="price" type="text" maxlength="255" value="<?=$form->price->getDisplayValue();?>" class="input">
	<div class="alert"><?=$form->price->error;?></div>

	<label for="image" class="label"><?=$form->image->title;?>:</label>
	<input id="image" name="image" type="file">
	<div class="alert"><?=$form->image->error;?></div>

	<label for="file" class="label"><?=$form->file->title;?>:</label>
	<input id="file" name="file" type="file">
	<div class="alert"><?=$form->file->error;?></div>

	<label for="name" class="label"><?=$form->name->title;?>:</label>
	<input id="name" name="name" type="text" maxlength="255" value="<?=$form->name->getDisplayValue();?>" class="input">
	<div class="alert"><?=$form->name->error;?></div>

	<label for="phone" class="label"><?=$form->phone->title;?>:</label>
	<input id="phone" name="phone" type="tel" maxlength="255" value="<?=$form->phone->getDisplayValue();?>" class="input">
	<div class="alert"><?=$form->phone->error;?></div>

	<label for="icq" class="label"><?=$form->icq->title;?>:</label>
	<input id="icq" name="icq" type="text" pattern="[0-9]{5,10}" value="<?=$form->icq->getDisplayValue();?>" class="input">
	<div class="alert"><?php if ($form->icq->error) echo $form->icq->error;?></div>

	<label for="skype" class="label"><?=$form->skype->title;?>:</label>
	<input id="skype" name="skype" type="text" value="<?=$form->skype->getDisplayValue();?>" class="input">
	<div class="alert"><?=$form->skype->error;?></div>

	<label for="url" class="label"><?=$form->url->title;?>:</label>
	<input id="url" name="url" type="url" maxlength="255" value="<?=$form->url->getDisplayValue();?>" class="input">
	<div class="alert"><?=$form->url->error;?></div>

	<label for="email" class="label"><span class="alert">*</span> <?=$form->email->title;?>:</label>
	<input id="email" name="email" type="text" maxlength="255" value="<?=$form->email->getDisplayValue();?>" required class="input">
	<div class="alert"><?=$form->email->error;?></div>

	<label for="city" class="label"><?=$form->city->title;?>:</label>
	<input id="city" name="city" type="text" maxlength="255" value="<?=$form->city->getDisplayValue();?>" class="input">
	<div class="alert"><?=$form->city->error;?></div>

	<label for="zip" class="label"><?=$form->zip->title;?>:</label>
	<input id="zip" name="zip" type="text" maxlength="255" pattern="[0-9]{6}" value="<?=$form->zip->getDisplayValue();?>" class="input">
	<div class="alert"><?=$form->zip->error;?></div>

	<label for="address" class="label"><?=$form->address->title;?>:</label>
	<input id="address" name="address" type="text" maxlength="255" value="<?=$form->address->getDisplayValue();?>" class="input">
	<div class="alert"><?=$form->address->error;?></div>

	<label for="company" class="label"><?=$form->company->title;?>:</label>
	<input id="company" name="company" type="text" maxlength="255" value="<?=$form->company->getDisplayValue();?>" class="input">
	<div class="alert"><?=$form->company->error;?></div>

	<label for="occupation" class="label"><?=$form->occupation->title;?>:</label>
	<input id="occupation" name="occupation" type="text" maxlength="255" value="<?=$form->occupation->getDisplayValue();?>" class="input">
	<div class="alert"><?=$form->occupation->error;?></div>

	<button type="submit" class="submit">Отправить</button>
	<div class="alert"><?=$form->error;?></div>
</form>